name: lovely_pets
version: "3.9"

services:
  core_service:
    build:
      context: .
      dockerfile: Dockerfile.back
      args:
        COMET_API_KEY: ${COMET_API_KEY}
        COMET_WORKSPACE: ${COMET_WORKSPACE}
        COMET_MODEL_NAME: ${COMET_MODEL_NAME}
        COMET_MODEL_NAME_VERSION: ${COMET_MODEL_NAME_VERSION}
        COMET_MODEL_FILE: ${COMET_MODEL_FILE}
    ports:
      - "80:80"  # Maps container port 80 to host port 80
    restart: unless-stopped
    networks:
      - lovely-pets-net

  front_service:
    build:
      context: .
      dockerfile: Dockerfile.front
      args:
        BACKEND_URL: http://localhost:80
    ports:
      - "8080:80"  # Maps container port 80 to host port 8080
    restart: unless-stopped
    networks:
      - lovely-pets-net
    depends_on:
      - core_service

# Shared Network
networks:
  lovely-pets-net:
    driver: bridge